<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Makosh.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Makosh.Core\Makosh.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Makosh.Tests" />
  </ItemGroup>

</Project>
