<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Makosh.Windows</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

    <ItemGroup>
    <ProjectReference Include="..\Makosh.Core\Makosh.Core.csproj" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <Using Remove="Windows.Media.SpeechSynthesis" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="silero\silero_worker.py">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Makosh.Tests" />
  </ItemGroup>

</Project>
